<?
global $MESS;

$MESS["SASP_PROMT"] = "�� ������ �������� ����� ������� <b>www.assist.ru</b>.";
$MESS["SASP_ACCOUNT_NO"] = "C��� �";
$MESS["SASP_ORDER_FROM"] = " �� ";
$MESS["SASP_ORDER_SUM"] = "����� � ������ �� �����:";
$MESS["SASP_ACTION"] = "��������";
$MESS["SASP_NOTES_TITLE"] = "��������� ������";
$MESS["SASP_NOTES"] = "������� ��������� �� ����� ����� ������������� ���������� ���������� ����������� �������. ��� ������ �������������� �� � �������������� ������: �� ������� ���� � 10:00 �� 18:00 (���������� �����).<br><br>� ����� � ��������� ������ � �������������� �������������� ���������� ��������� ���������� �� ������ Visa � Eurocard/Mastercard ��� ���������� ����, ���������������� ��� �������� CVV2/CVC2 (CVV2 ��� CVC2 - ���������� ����������� �����, ���������� �� �������� ������� ����� ����� �� ������), ������� ���������� ��������� ����������� � ��������� �� �����.<br><br>� ������� <a href=\"http://www.assist.ru/\">������</a> ������������ �������� �������������� �������������� SSL ��������� ��� �������� ���������������� ���������� �� ������� �� ������ <a href=\"http://www.assist.ru/\">������� ������</a> ��� ���������� ���������.<br><br>���������� �������� ���������� �������������� �� �������� ���������� �����, ����� ������� ����������� ����������.<br><br>��������� ���������� ���������������� ������ �������  ������������ � �������������� ������ <a href=\"http://www.alfabank.ru/\">�� \"�����-����\"</a>. ����� �������, �����, ���� �������� �� ����� �������� ������������ � ���������� ������ �������.<br><br>";
$MESS["SASP_NOTES_TITLE1"] = "������������ ������������ ����������";
$MESS["SASP_NOTES1"] = "��� ������ ���������� �� �������������������� ������� �� ����� �������� �� ������� �� ������ ������� ������������ �������� SSL 3.0, ���������� ������� (128 bit) ����� ��������� <a href=\"https://www.thawte.com\">Thawte</a> - ���������� ������� ������ �������� ������������.<br><br>�� ������ <a href=\"https://sealinfo.thawte.com/thawtesplash?form_file=fdf/thawtesplash.fdf&dn=WWW.ASSIST.RU&lang=en\">��������� ����������� �����������</a> ������� ������.";
$MESS["SASP_AS000"] = "����������� ������� ���������";
$MESS["SASP_AS001"] = "����������� ������� ��������� (� CVC2)";
$MESS["SASP_AS010"] = "��������������� ������� ���������";
$MESS["SASP_AS011"] = "��������������� ������� ��������� (� CVC2)";
$MESS["SASP_AS020"] = "��������������� ������� ���������";
$MESS["SASP_AS100"] = "����� � �����������";
$MESS["SASP_AS101"] = "����� � �����������. ��������� ����� ���������� ��������";
$MESS["SASP_AS102"] = "����� � �����������. ������������ �������";
$MESS["SASP_AS104"] = "����� � �����������. �������� ���� �������� �����";
$MESS["SASP_AS105"] = "����� � �����������. �������� �����";
$MESS["SASP_AS106"] = "����� � �����������. �������� PIN";
$MESS["SASP_AS107"] = "����� � �����������. ������ ������ ������";
$MESS["SASP_AS108"] = "����� � �����������. ���������� �� �������������";
$MESS["SASP_AS109"] = "����� � �����������. �������� ����� �������� Assist";
$MESS["SASP_AS200"] = "��������� �����������";
$MESS["SASP_AS300"] = "����������� � ��������. �����";
$MESS["SASP_AS400"] = "������� � ������ ����������� �� ����������";
$MESS["SASP_AS998"] = "������ �������. ��������� � ASSIST";
$MESS["SALE_ASSIST_DESCRIPTION"] = "<a href=\"http://www.assist.ru\" target=\"_blank\">http://www.assist.ru</a>";
$MESS["SALE_ASSIST_SHOP_IDP_NAME"] = "��� ��������";
$MESS["SALE_ASSIST_SHOP_IDP_DESCR"] = "��� ��������, ������� ������� �� Assist.ru";
$MESS["SALE_ASSIST_SHOP_LOGIN_NAME"] = "�����";
$MESS["SALE_ASSIST_SHOP_LOGIN_DESCR"] = "�����, ������� ������� �� Assist.ru";
$MESS["SALE_ASSIST_SHOP_PASSWORD_NAME"] = "������";
$MESS["SALE_ASSIST_SHOP_PASSWORD_DESCR"] = "������, ������� ������� �� Assist.ru";
$MESS["SALE_ASSIST_FIRST_NAME_NAME"] = "��� ����������";
$MESS["SALE_ASSIST_FIRST_NAME_DESC"] = "";
$MESS["SALE_ASSIST_LAST_NAME_NAME"] = "������� ����������";
$MESS["SALE_ASSIST_LAST_NAME_DESC"] = "";
$MESS["SALE_ASSIST_DEMO_NAME"] = "������ � �������� ������";
$MESS["SALE_ASSIST_EMAIL_NAME"] = "E-mail ����������";
$MESS["SALE_ASSIST_EMAIL_DESC"] = "";
$MESS["SALE_ASSIST_PHONE_NAME"] = "������� ����������";
$MESS["SALE_ASSIST_PHONE_DESC"] = "";
$MESS["SALE_ASSIST_ADDRESS_NAME"] = "����� ����������";
$MESS["SALE_ASSIST_ADDRESS_DESC"] = "";
$MESS["SALE_ASSIST_MIDDLE_NAME_NAME"] = "�������� ����������";
$MESS["SALE_ASSIST_MIDDLE_NAME_DESC"] = "";
$MESS["SALE_ASSIST_PAYMENT_NAME"] = "������ ������";
$MESS["SALE_ASSIST_PAYMENT_CardPayment_NAME"] = "������������ ������ �� ��������� �����";
$MESS["SALE_ASSIST_PAYMENT_WalletPayment_NAME"] = "������������ SET-�����������";
$MESS["SALE_ASSIST_PAYMENT_WebMoneyPayment_NAME"] = "������������ ��������� ������� WebMoney Transfer";
$MESS["SALE_ASSIST_PAYMENT_EPortPayment_NAME"] = "������������ ��������� ������� E-Port";
$MESS["SALE_ASSIST_PAYMENT_KreditPilotPayment_NAME"] = "������������ ��������� ������� KreditPilot";
$MESS["SALE_ASSIST_PAYMENT_PayCashPayment_NAME"] = "������������ ��������� ������� PayCash";
$MESS["SALE_ASSIST_PAYMENT_CardPayment_DESC"] = "1 - ������������, 0 - �� ������������";
$MESS["SALE_ASSIST_PAYMENT_WalletPayment_DESC"] = "1 - ������������, 0 - �� ������������";
$MESS["SALE_ASSIST_PAYMENT_EPortPayment_DESC"] = "1 - ������������, 0 - �� ������������";
$MESS["SALE_ASSIST_PAYMENT_KreditPilotPayment_DESC"] = "1 - ������������, 0 - �� ������������";
$MESS["SALE_ASSIST_PAYMENT_PayCashPayment_DESC"] = "1 - ������������, 0 - �� ������������";
$MESS["SALE_ASSIST_PAYMENT_WebMoneyPayment_DESC"] = "1 - ������������, 0 - �� ������������";

$MESS["SALE_ASSIST_PAYMENT_RapidaPayment_NAME"] = "������������ ��������� ������� Rapida";
$MESS["SALE_ASSIST_PAYMENT_RapidaPayment_DESC"] = "1 - ������������, 0 - �� ������������";
$MESS["SALE_ASSIST_PAYMENT_AssistIDCCPayment_NAME"] = "������������ ������ ��������� ������ � �������������� Assist�ID";
$MESS["SALE_ASSIST_PAYMENT_AssistIDCCPayment_DESC"] = "1 - ������������, 0 - �� ������������";
$MESS["SALE_ASSIST_PAYMENT_EPBeelinePayment_NAME"] = "������������ ��������� ������� ������";
$MESS["SALE_ASSIST_PAYMENT_EPBeelinePayment_DESC"] = "1 - ������������, 0 - �� ������������";

$MESS["SALE_ASSIST_PAYMENT_YMPayment_NAME"] = "������������ ��������� ������� YandexMoney";
$MESS["SALE_ASSIST_PAYMENT_QIWIPayment_NAME"] = "������������ ��������� ������� QIWI";
$MESS["SALE_ASSIST_PAYMENT_YMPayment_DESC"] = "1 - ������������, 0 - �� ������������";
$MESS["SALE_ASSIST_PAYMENT_QIWIPayment_DESC"] = "1 - ������������, 0 - �� ������������";
$MESS["SALE_ASSIST_AUTOPAY_NAME"] = "������������� ���������� ����� ��� ��������� ��������� ������� ������ �� ������";
$MESS["SALE_ASSIST_AUTOPAY_DESC"] = "Y - ������������, N - �� ������������";
$MESS["SALE_ASSIST_SHOP_SECRET_WORLD_NAME"] = "��������� �����";
$MESS["SALE_ASSIST_SHOP_SECRET_WORLD_DESCR"] = "��� ��������� ����������� �������� � �������������� ������. �������� � ������ �������� Assit � \"��������� ��������\" �� ������� \"��������� �������� ����������� ��������\"";

$MESS["SALE_ASSIST_DEMO_DESC"] = "������� �������� �������� ��� ��������� ������. � �������� ������ ������ ��� ������ ������ ����� ������������ �������� ����� �� ������������ Assist";

$MESS["SALE_ASSIST_SHOULD_PAY"] = "����� � ������";
$MESS["SALE_ASSIST_DESC_SHOULD_PAY"] = "";
$MESS["SALE_ASSIST_CURRENCY"] = "������ ������";
$MESS["SALE_ASSIST_DESC_CURRENCY"] = "";
$MESS["SALE_ASSIST_ORDER_ID"] = "����� ������";
$MESS["SALE_ASSIST_DESC_ORDER_ID"] = "����� ������ � ����� ��������-��������";
$MESS["SALE_ASSIST_SUCCESS_URL"] = "����� ��� �������� ������";
$MESS["SALE_ASSIST_DESC_SUCCESS_URL"] = "����� �������� (�� ���-����� ��������) ��� ��������������� ����������� ��� �������� �������";
$MESS["SALE_ASSIST_FAIL_URL"] = "����� ��� ������ ������";
$MESS["SALE_ASSIST_DESC_FAIL_URL"] = "����� �������� (�� ���-����� ��������) ��� ��������������� ����������� ��� ���������� �������";
$MESS["SALE_ASSIST_DATE_INSERT"] = "���� �������� ������";
$MESS["SALE_ASSIST_DESC_DATE_INSERT"] = "";

$MESS["SASP_IP"] = "� ��������";
$MESS["SASP_D"] = "������� ������������� ������";
$MESS["SASP_A"] = "�������";
$MESS["SASP_PA"] = "������� ��������";
$MESS["SASP_PD"] = "����������� ��������";
$MESS["SASP_C"] = "�������";
$MESS["SASP_PC"] = "������� ��������";
$MESS["SASP_DEC"] = "��������";
$MESS["SASP_T"] = "������ �� ��������� �������";

$MESS["SASPD_IP"] = "����� ������";
$MESS["SASPD_D"] = "�������� ������ �� ������� ������ ������� ��������� �� ������������� ���������";
$MESS["SASPD_A"] = "�������� ������ �� ������� ������ ������� ���������";
$MESS["SASPD_PA"] = "�������� ������ ��������� �� ����� ����� ������ (�� ������������)";
$MESS["SASPD_PD"] = "������������� ������ ��������� �� ����� ����� ������";
$MESS["SASPD_C"] = "������� �� ������ ����� ������";
$MESS["SASPD_PC"] = "������� �� ����� ����� ������";
$MESS["SASPD_DEC"] = "������ ��������� ���������";
$MESS["SASPD_T"] = "����� �������� �� ����-����";
?>