<?
$nameUTF = array(
    "CommerceInfo" => "����������������������",
    "Company" => "����������",
    "Catalog" => "�������",
    "Product" => "�����",
    "ID" => "�������������",
    "Name" => "������������",
    "DisplayName" => "������������������������",
    "Amount" => "����������",
    "Price" => "����",
    "Property" => "��������",
    "Description" => "��������",
    "Unit" => "�������",
    "DataType" => "���������",
    "DisplayOnSite" => "������������",
    "Multiple" => "���������������",
    "DefaultValue" => "�������������������",
    "PropertyReference" => "����������������",
    "CatalogID" => "���������������������",
    "IdInCatalog" => "����������������������",
    "PropertyId" => "���������������������",
    "PropertyVariant" => "���������������",
    "ParentCategory" => "��������",
    "Category" => "������",
    "OffersList" => "����������������",
    "Currency" => "������",
    "Offer" => "�����������",
    "ProductId" => "�������������������",
    "PropertyValue" => "����������������",
    "Value" => "��������",
    "CategoryReference" => "��������������",
    "CommerceInfoVersion" => "�����������",
    "Yandex" => "yml_catalog"
);
?>