<?php
$MESS["SALE_HANDLERS_PAY_SYSTEM_ASSIST_DESCRIPTION"] = "������ ������������� ������ ������-�������� <b>&laquo;������.�����&raquo;</b>.<br /><br />����� � ������ �� �����: ";
$MESS["SALE_HANDLERS_PAY_SYSTEM_ASSIST_WARNING_RETURN"] = "<b>�������� ��������:</b> ���� �� ���������� �� �������, ��� �������� ����� ��� �������� ���������� � �������.";
$MESS["SALE_HANDLERS_PAY_SYSTEM_ASSIST_BUTTON_PAID"] = "��������";
$MESS["SALE_HANDLERS_PAY_SYSTEM_ASSIST_PROMT"] = "�� ������ �������� ����� ������� <b>www.assist.ru</b>.";
$MESS["SALE_HANDLERS_PAY_SYSTEM_ASSIST_ACCOUNT_NO"] = "C��� �";
$MESS["SALE_HANDLERS_PAY_SYSTEM_ASSIST_ORDER_FROM"] = " �� ";
$MESS["SALE_HANDLERS_PAY_SYSTEM_ASSIST_ORDER_SUM"] = "����� � ������ �� �����:";
$MESS["SALE_HANDLERS_PAY_SYSTEM_ASSIST_ACTION"] = "��������";
$MESS["SALE_HANDLERS_PAY_SYSTEM_ASSIST_NOTES_TITLE"] = "��������� ������";
$MESS["SALE_HANDLERS_PAY_SYSTEM_ASSIST_NOTES"] = "������� ��������� �� ����� ����� ������������� ���������� ���������� ����������� �������. ��� ������ �������������� �� � �������������� ������: �� ������� ���� � 10:00 �� 18:00 (���������� �����).<br><br>� ����� � ��������� ������ � �������������� �������������� ���������� ��������� ���������� �� ������ Visa � Eurocard/Mastercard ��� ���������� ����, ���������������� ��� �������� CVV2/CVC2 (CVV2 ��� CVC2 - ���������� ����������� �����, ���������� �� �������� ������� ����� ����� �� ������), ������� ���������� ��������� ����������� � ��������� �� �����.<br><br>� ������� <a href=\"http://www.assist.ru/\">������</a> ������������ �������� �������������� �������������� SSL ��������� ��� �������� ���������������� ���������� �� ������� �� ������ <a href=\"http://www.assist.ru/\">������� ������</a> ��� ���������� ���������.<br><br>���������� �������� ���������� �������������� �� �������� ���������� �����, ����� ������� ����������� ����������.<br><br>��������� ���������� ���������������� ������ �������  ������������ � �������������� ������ <a href=\"http://www.alfabank.ru/\">�� \"�����-����\"</a>. ����� �������, �����, ���� �������� �� ����� �������� ������������ � ���������� ������ �������.<br><br>";
$MESS["SALE_HANDLERS_PAY_SYSTEM_ASSIST_NOTES_TITLE1"] = "������������ ������������ ����������";
$MESS["SALE_HANDLERS_PAY_SYSTEM_ASSIST_NOTES1"] = "��� ������ ���������� �� �������������������� ������� �� ����� �������� �� ������� �� ������ ������� ������������ �������� SSL 3.0, ���������� ������� (128 bit) ����� ��������� <a href=\"https://www.thawte.com\">Thawte</a> - ���������� ������� ������ �������� ������������.<br><br>�� ������ <a href=\"https://sealinfo.thawte.com/thawtesplash?form_file=fdf/thawtesplash.fdf&dn=WWW.ASSIST.RU&lang=en\">��������� ����������� �����������</a> ������� ������.";