<?

global $MESS;

$MESS["CHRP_SHOULD_PAY"] = "����� � ������";
$MESS["CHRP_DESC_SHOULD_PAY"] = "";
$MESS["CHRP_PRODUCT_ID"] = "��� ������";
$MESS["CHRP_DESC_PRODUCT_ID"] = "���������� ��� ������ ��� ������ �� ����� Chronopay";
$MESS["CHRP_PRODUCT_NAME"] = "������������ ������";
$MESS["CHRP_DESC_PRODUCT_NAME"] = "������������ ������  � ������";
$MESS["CHRP_ORDER_ID"] = "����� ������";
$MESS["CHRP_DESC_ORDER_ID"] = "����� ������ � ����� ��������-��������";
$MESS["CHRP_CB_URL"] = "����� ��� ����������� �� ������";
$MESS["CHRP_DESC_CB_URL"] = "URL ������� (�� ���-����� ��������) ��������������� ���������� � ���������� �������";
$MESS["CHRP_DECLINE_URL"] = "����� ��� ������ ������";
$MESS["CHRP_DESC_DECLINE_URL"] = "URL (�� ���-����� ��������) ��� ��������������� ����������� ��� ���������� �������";
$MESS["CHRP_SUCCESS_URL"] = "����� ��� �������� ������";
$MESS["CHRP_DESC_SUCCESS_URL"] = "URL (�� ���-����� ��������) ��� ��������������� ����������� ��� �������� �������";
$MESS["CHRP_SHARED"] = "������� ����� ��������";
$MESS["CHRP_DESC_SHARED"] = "������� ���� (shared secret) ������������ � �������� ���������� �������������� �� ��������� ����������� ������ �������� � ��������������� ���������� �� �����������";
$MESS["CHRP_YANDEX_FORWARD"] = "��������������� � ��������� ������� Yandex";
$MESS["CHRP_DESC_YANDEX_FORWARD"] = "������� �������� �������� ��� ��������������� ��������������� � ��������� ������� Yandex";
$MESS["CHRP_WEBMONEY_FORWARD"] = "��������������� � ��������� ������� WebMoney";
$MESS["CHRP_DESC_WEBMONEY_FORWARD"] = "������� �������� �������� ��� ��������������� ��������������� � ��������� ������� WebMoney";
$MESS["CHRP_QIWI_FORWARD"] = "��������������� � ��������� ������� Qiwi";
$MESS["CHRP_DESC_QIWI_FORWARD"] = "������� �������� �������� ��� ��������������� ��������������� � ��������� ������� Qiwi";
$MESS["CHRP_PAY_BUTTON"] = "�������� ������ ������";
$MESS["CHRP_DESC_PAY_BUTTON"] = "";
$MESS["CHRP_CS2"] = "�������������� �������� 1";
$MESS["CHRP_DESC_CS2"] = "�������� ������ � ������� ������� ����������� � ������������ ��� ���������� � ������� � �������� ������";
$MESS["CHRP_CS3"] = "�������������� �������� 2";
$MESS["CHRP_DESC_CS3"] = "�������� ������ � ������� ������� ����������� � ������������ ��� ���������� � ������� � �������� ������";
$MESS["CHRP_LANGUAGE"] = "���� ���������� ����� Chronopay";
$MESS["CHRP_DESC_LANGUAGE"] = "��������� ��������: En � ���������� (�� ���������); Ru � �������;	Nl � �����������; Es - ���������;";
$MESS["CHRP_F_NAME"] = "��� ������������";
$MESS["CHRP_DESC_F_NAME"] = "";
$MESS["CHRP_S_NAME"] = "������� ������������";
$MESS["CHRP_DESC_S_NAME"] = "";
$MESS["CHRP_STREET"] = "����� ����������";
$MESS["CHRP_DESC_STREET"] = "";
$MESS["CHRP_CITY"] = "����� ����������";
$MESS["CHRP_DESC_CITY"] = "";
$MESS["CHRP_STATE"] = "���� ����������";
$MESS["CHRP_DESC_STATE"] = "������ ��� ���";
$MESS["CHRP_ZIP"] = "�������� ������";
$MESS["CHRP_DESC_ZIP"] = "";
$MESS["CHRP_COUNTRY"] = "������ ����������";
$MESS["CHRP_DESC_COUNTRY"] = "2-� ��������� ��� (<a href='http://www.iso.org/iso/country_codes/iso_3166_code_lists/english_country_names_and_code_elements.htm#lr'>ISO 3166-1 alpha-2</a>)";
$MESS["CHRP_PHONE"] = "�������";
$MESS["CHRP_DESC_PHONE"] = "����� �������� � ������������� �������";
$MESS["CHRP_EMAIL"] = "����������� �����";
$MESS["CHRP_DESC_EMAIL"] = "";
$MESS["CHRP_ORDER_UNIQ"] = "������������ ���������� �������� ������������ ������ ������";
$MESS["CHRP_DESC_ORDER_UNIQ"] = "������� �������� �������� ��� ������������� ������� �����������";
?>